### ISSUE TITLE
cursor invisible in column 0

### ISSUE THREAD

**Issue by cben** [cben/mathdown#179]
The cursor is invisible when at left-most position.

codemirror.css sets:
```css
.CodeMirror pre {
  padding: 0 4px; /* Horizontal padding of content */
}
```
This is overridden by my renderLine callback for indented soft-wrapping, it sets `style="text-indent: -0ex; padding-left: 0ex;"` on the pre element :-(

Chromium 63.0.3239.108, Linux, but probably everywhere.
